#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>


#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_12
#define AUDIO_I2S_GPIO_WS GPIO_NUM_10
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_11
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_9
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_8

#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_14
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_13
#define AUDIO_CODEC_ES8311_ADDR  0x30
#define AUDIO_CODEC_ES7210_ADDR  0x82

#define POWER_CHARGING_GPIO GPIO_NUM_16

#define BUILTIN_LED_GPIO        GPIO_NUM_6
#define LED_STRIP_GPIO       GPIO_NUM_7
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_42
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#define MOTOR_PWM_GPIO   GPIO_NUM_5
#define MOTOR_ADC_GPIO   GPIO_NUM_4

#define RC522_SPI_MISO_GPIO    GPIO_NUM_40
#define RC522_SPI_MOSI_GPIO    GPIO_NUM_39
#define RC522_SPI_SCLK_GPIO    GPIO_NUM_38
#define RC522_SPI_SCANNER_SDA_GPIO GPIO_NUM_41
#define RC522_SCANNER_RST_GPIO     GPIO_NUM_NC // soft-reset

#define ML307_RX_PIN GPIO_NUM_21
#define ML307_TX_PIN GPIO_NUM_18
#endif // _BOARD_CONFIG_H_